sudo: required
language: node_js
node_js:
  - "lts/*"
go:
  - master
install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.40.3/hugo_0.40.3_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - npm install
before_script:
  - npm install -g gulp-cli
script: gulp
deploy:
  provider: pages
  edge:
      branch: pages-ivar-set
  local-dir: public
  target-branch: master
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: source
cache:
  directories:
    - node_modules
notifications:
  email:
    on_success: never
