baseURL: "https://inwardmovement.github.io/"
languageCode: "en"
title: "Inward Movement"
disableLiveReload: true
# disableFastRender: true
metaDataFormat: yaml
rssLimit: 10
enableRobotsTXT: true
disableKinds: ["taxonomy", "taxonomyTerm"]
# ignoreFiles: ["static//css//.*.css$", "static//js//.*.js$"]
params:
  description: "Writer, musician, activist"
  author: "Victor Massé"
author:
  name: "Victor Massé"
blackfriday:
  angledQuotes: true
  extensions:
    - hardLineBreak
    - noEmptyLineBeforeBlock
footnoteReturnLinkContents: "↑"
menu:
  mainleft:
    - Name: "Poems"
      URL: "/poems/"
      Identifier: "poems"
      weight: 1
    - Name: "Articles"
      URL: "/articles/"
      Identifier: "articles"
      weight: 2
    - Name: "Music"
      URL: "/music/"
      Identifier: "music"
      weight: 3
    - Name: "Activism"
      URL: "/activism/"
      Identifier: "activism"
      weight: 4
  mainright:
    - Name: "About"
      URL: "/about/"
      Identifier: "about"
      weight: 1
  recueils:
    - Name: "Fleurs persistantes"
      URL: "/poems/fleurspersistantes/"
      Identifier: "fleurspersistantes"
      weight: 1
    - Name: "SuperEro"
      URL: "/poems/superero/"
      Identifier: "superero"
      weight: 2
    - Name: "Poudre à rêver"
      URL: "/poems/poudrearever/"
      Identifier: "poudrearever"
      weight: 3
    - Name: "Méditations"
      URL: "/poems/meditations/"
      Identifier: "meditations"
      weight: 4
    - Name: "Érosphère"
      URL: "/poems/erosphere/"
      Identifier: "erosphere"
      weight: 5
