baseURL: "https://inwardmovement.github.io/"
languageCode: "fr"
defaultContentLanguage: "fr"
title: "Inward Movement"
canonifyURLs: true
disableLiveReload: true
metaDataFormat: yaml
rssLimit: 10
enableRobotsTXT: true
disableKinds: ["taxonomy", "taxonomyTerm"]
params:
  description: "Auteur"
  author: "Victor Massé"
author:
  name: "Victor Massé"
blackfriday:
  angledQuotes: true
  extensions:
    - hardLineBreak
    - noEmptyLineBeforeBlock
footnoteReturnLinkContents: "↑"
menu:
  main:
    - Name: "Poèmes"
      URL: "/poemes/"
      Identifier: "poemes"
      weight: 1
    - Name: "Articles"
      URL: "/articles/"
      Identifier: "articles"
      weight: 2
  footer:
    - Name: "GitHub"
      URL: "https://github.com/inwardmovement/inwardmovement.github.io/"
      Identifier: "github"
      weight: 1
  recueils:
    - Name: "Fleurs persistantes"
      URL: "/poemes/fleurspersistantes/"
      Identifier: "fleurspersistantes"
      weight: 1
    - Name: "SuperEro"
      URL: "/poemes/superero/"
      Identifier: "superero"
      weight: 2
    - Name: "Poudre à rêver"
      URL: "/poemes/poudrearever/"
      Identifier: "poudrearever"
      weight: 3
    - Name: "Méditations"
      URL: "/poemes/meditations/"
      Identifier: "meditations"
      weight: 4
    - Name: "Érosphère"
      URL: "/poemes/erosphere/"
      Identifier: "erosphere"
      weight: 5
