baseURL: "https://inwardmovement.github.io/"
languageCode: "fr"
defaultContentLanguage: "fr"
title: "Inward Movement"
canonifyURLs: false
relativeURLs: true
disableFastRender: true
disableLiveReload: true
metaDataFormat: yaml
rssLimit: 10
enableRobotsTXT: true
disableKinds: ["taxonomy", "taxonomyTerm"]
params:
  description: "Auteur, musicien, activiste, consultant"
  author: "Victor Massé"
author:
  name: "Victor Massé"
markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: false
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: true
      unsafe: true
      xHTML: false
  tableOfContents:
    startLevel: 1
    endLevel: 5
footnoteReturnLinkContents: "↑"
menu:
  main:
    - Name: "Accueil"
      URL: "/"
      Identifier: "accueil"
      weight: 1
    - Name: "Poèmes"
      URL: "/poemes/"
      Identifier: "poemes"
      weight: 2
    - Name: "Articles"
      URL: "/articles/"
      Identifier: "articles"
      weight: 3
  footer:
    - Name: "Mentions légales"
      URL: "/mentions-legales/"
      Identifier: "mentions-legales"
      weight: 1
  recueils:
    - Name: "Fleurs persistantes"
      URL: "/poemes/fleurspersistantes/"
      Identifier: "fleurspersistantes"
      weight: 1
    - Name: "SuperEro"
      URL: "/poemes/superero/"
      Identifier: "superero"
      weight: 2
    - Name: "Poudre à rêver"
      URL: "/poemes/poudrearever/"
      Identifier: "poudrearever"
      weight: 3
    - Name: "Méditations"
      URL: "/poemes/meditations/"
      Identifier: "meditations"
      weight: 4
    - Name: "Érosphère"
      URL: "/poemes/erosphere/"
      Identifier: "erosphere"
      weight: 5
