name: ci-cd-source

on:
  push:
    branches:
      - source

env:
  PRODUCTION: true
  HUGO_VERSION: '0.65.3'
  NODE_VERSION: '12.14.0'
  GITHUB_PAT: ${{ secrets.PERSONAL_TOKEN_GH_PAGES }}

jobs:
  build-and-deploy:
    name: Build & deploy
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
      if: success()
    - name: Install dependencies
      run: |
        npm ci
        npm i -g gulp-cli postcss-cli autoprefixer
      if: success()
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: ${{ env.HUGO_VERSION }}
        extended: true
      if: success()
    - name: Build site
      run: npm run build-prod
      if: success()
    - name: Deploy site
      uses: crazy-max/ghaction-github-pages@v1
      with:
        target_branch: master
        build_dir: public
      if: success()
    - name: Upload site
      uses: actions/upload-artifact@v1
      with:
        name: public
        path: public
      if: success()
