name: ci-cd-source

on:
  push:
    branches:
      - source

env:
  PRODUCTION: true
  NODE_VERSION: '12.14.0'
  HUGO_VERSION: '0.64.0'
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
  GITHUB_PAT: ${{ secrets.PERSONAL_TOKEN_GH_PAGES }}

jobs:
  build-and-deploy:
    name: Build & deploy
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
      if: success()
    - name: Install dependencies
      run: |
        npm ci
        npm i -g gulp-cli postcss-cli autoprefixer
      if: success()
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: ${{ env.HUGO_VERSION }}
        extended: true
      if: success()
    - name: Build site
      run: npm run build-prod
      if: success()
    - name: Deploy site
      uses: crazy-max/ghaction-github-pages@v1
      with:
        target_branch: master
        build_dir: public
      if: success()
    - name: Notify Discord on failure
      uses: rjstone/discord-webhook-notify@v1
      if: failure()
      with:
        text: CI/CD failed
        webhookUrl: ${{ env.DISCORD_WEBHOOK }}
    - uses: actions/upload-artifact@v1
      with:
        name: site
        path: public
